bipedal-locomotion-framework: BipedalLocomotion::Estimators::RecursiveLeastSquare Class Reference
BipedalLocomotion::Estimators::RecursiveLeastSquare Class Reference
RecursiveLeastSquare contains the implementation of the Recursive least square filter described in Lennart Ljung - System Identification Theory for the User (1999, Prentice Hall).
#include <BipedalLocomotion/Estimators/RecursiveLeastSquare.h>
Public Member Functions
bool initialize (std::weak_ptr< ParametersHandler::IParametersHandler > handlerWeak)
Initialize the filter.
void setRegressorFunction (std::function< iDynTree::MatrixDynSize(void)> regressor)
Set the regressor regressor fucntion that return an iDynTree::MatrixDynSize containing the regressor of the system.
void setMeasurements (const iDynTree::VectorDynSize &measurements)
Set the measurements measurements vector containing all the measurements.
bool advance ()
Compute one step of the filter.
const iDynTree::VectorDynSize & parametersExpectedValue () const
Get the expected value of the estimated parameters.
const iDynTree::MatrixDynSize & parametersCovarianceMatrix () const
Get the Covariance matrix of the estimated parameters.
Detailed Description
RecursiveLeastSquare contains the implementation of the Recursive least square filter described in Lennart Ljung - System Identification Theory for the User (1999, Prentice Hall).
Chapter 11 Section 2.
Definition at line 28 of file RecursiveLeastSquare.h.
Member Function Documentation
advance()
bool RecursiveLeastSquare::advance ()
Compute one step of the filter.
Returns
true in case of success, false otherwise
Definition at line 96 of file RecursiveLeastSquare.cpp.
References std::endl().
initialize()
bool RecursiveLeastSquare::initialize (std::weak_ptr< ParametersHandler::IParametersHandler > handlerWeak)
Initialize the filter.
Note
The following parameter are required by the filter:
"measurement_covariance" vector containing the covariance of the measurements. We assume that the measurements are uncorrelated (furthermore since the model of the noise is Gaussian the random variable are also independent) Since the variable are independent we are interested only on the element in the diagonal of the matrix
"lambda" double containing the filter gain. (The recursive least square filter is equivalent to a kalman filter if lambda is equal to 1)
"state" vector containing the initial guess of the state
"state_covariance" vector containing the diagonal matrix of the covariance of the state
Parameters
handlerWeak weak pointer to a ParametersHandler::IParametersHandler interface Derived particular implementation of the IParameterHandler
Returns
true in case of success, false otherwise
Definition at line 17 of file RecursiveLeastSquare.cpp.
References std::endl(), and std::weak_ptr< T >::lock().
parametersCovarianceMatrix()
const iDynTree::MatrixDynSize & RecursiveLeastSquare::parametersCovarianceMatrix () const
Get the Covariance matrix of the estimated parameters.
Returns
covariance matrix
Definition at line 146 of file RecursiveLeastSquare.cpp.
parametersExpectedValue()
const iDynTree::VectorDynSize & RecursiveLeastSquare::parametersExpectedValue () const
Get the expected value of the estimated parameters.
Returns
vector containing the expected value of the estimated parameters
Definition at line 141 of file RecursiveLeastSquare.cpp.
setMeasurements()
void RecursiveLeastSquare::setMeasurements (const iDynTree::VectorDynSize & measurements)
Set the measurements measurements vector containing all the measurements.
Definition at line 135 of file RecursiveLeastSquare.cpp.
setRegressorFunction()
void RecursiveLeastSquare::setRegressorFunction (std::function< iDynTree::MatrixDynSize(void)> regressor)
Set the regressor regressor fucntion that return an iDynTree::MatrixDynSize containing the regressor of the system.
Definition at line 91 of file RecursiveLeastSquare.cpp.
The documentation for this class was generated from the following files:
Estimators/include/BipedalLocomotion/Estimators/RecursiveLeastSquare.h
Estimators/src/RecursiveLeastSquare.cpp